name: Test SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  actions: read

jobs:
  sonarqube:
    name: Test SonarQube Scan
    uses: ./.github/workflows/test-reusable-sonarqube.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.WZ_SONAR_TOKEN }}
